apiVersion: v1
kind: Service
metadata:
  name: logger-service
  labels:
    app: logger
spec:
  ports:
  - port: 8083
    targetPort: 8083
  - port: 5001
    targetPort: 5001
  - port: 50001
    targetPort: 50001
  selector:
    app: logger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-deployment
  labels:
    app: logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: calvarado2004/microservices-go-logging:latest
        env:
        - name: MONGO_USER
          value: "mongo"
        - name: MONGO_PASSWORD
          value: "mongo"
        ports:
        - containerPort: 8083
        - containerPort: 5001
        - containerPort: 50001