apiVersion: v1
kind: Service
metadata:
  name: logger-service
  labels:
    app: logger
spec:
  ports:
  - port: 8083
    targetPort: 8083
    name: "web"
  - port: 5001
    targetPort: 5001
    name: "rpc"
  - port: 50001
    targetPort: 50001
    name: "grpc"
  selector:
    app: logger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-deployment
  labels:
    app: logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: calvarado2004/microservices-go-logging:latest
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          exec:
            command:
              - sh
              - -ec
              - 'wget --no-verbose --tries=1 --spider http://127.0.0.1:8083/ping || exit 1'
          initialDelaySeconds: 7
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
              - sh
              - -ec
              - 'wget --no-verbose --tries=1 --spider http://127.0.0.1:8083/ping || exit 1'
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        env:
        - name: MONGO_USER
          value: "mongo"
        - name: MONGO_PASSWORD
          value: "mongo"
        ports:
        - containerPort: 8083
          name: "web"
        - containerPort: 5001
          name: "rpc"
        - containerPort: 50001
          name: "grpc"
