kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: portworx-db-sc
provisioner: pxd.portworx.com
parameters:
  repl: "3"
  io_profile: "db_remote"
  io_priority: "high"
  cow_ondemand: "false"
  async_io: "true"
  early_ack: "true"
  nodiscard: "true"
allowVolumeExpansion: true
